# unbind ctrl-b (tmux prefix key)
unbind C-b
# and set the tmux prefix key to alt-b (-g is global, ie all sessions/panes/etc)
set-option -g prefix M-b

# a bit wonky, but the prefix key is also send to the terminal
bind-key M-b send-prefix

# Toggle terminal on bottom with ctrl-j
bind-key -n C-j run-shell "~/.tmux/toggle-terminal.sh"

# hide tmux status bar
set -g status off

# enable mouse
set -g mouse on

# With focus-events enabled, programs inside tmux can detect when
# The terminal window/tab becomes focused vs unfocused.
# The tmux client becomes active/inactive (for example, when you alt-tab away and back).
setw -g focus-events on

# Allows certain terminal escape sequences from programs inside tmux to “pass through” tmux to the outer terminal emulator.
# examples include some kinds of clipboard operations, graphics protocols, or other terminal capabilities that tmux might otherwise filter or reinterpret
set-option -g allow-passthrough on

# idk if needed, when you have correct terminfo files
# tmux will advertise/enable 24-bit color for programs inside tmux (so themes in Vim/Neovim, bat, lsd, etc. look correct).
# If you connect from a terminal that doesn’t support truecolor, colors may look wrong.
# set-option -ga terminal-overrides ",*:Tc"
